apiVersion: v1
description: High Performance, Kubernetes Native Object Storage
name: minio
version: 6.1.1
appVersion: master
keywords:
- storage
- object-storage
- S3
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
maintainers:
- name: Minio
  email: dev@minio.io
